export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGOUT = 'LOGOUT';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const DETAILS_USER_REQUEST = 'DETAILS_USER_REQUEST';
export const DETAILS_USER_SUCCESS = 'DETAILS_USER_SUCCESS';
export const DETAILS_USER_FAIL = 'DETAILS_USER_FAIL';

export const UPDATE_PROFILE_USER_REQUEST = 'UPDATE_PROFILE_USER_REQUEST';
export const UPDATE_PROFILE_USER_SUCCESS = 'UPDATE_PROFILE_USER_SUCCESS';
export const UPDATE_PROFILE_USER_FAIL = 'UPDATE_PROFILE_USER_FAIL';

export const RESET_USER_UPDATE_PROFILE = 'RESET_USER_UPDATE_PROFILE';